version: "3.3"
services:

  db:
    container_name: mysqldb
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Oracle42
      #MYSQL_DATABASE: pipeline_db
    ports:
      - 3306:3306
    expose:
      - 3306
    
    volumes:
      #- /home/marcelo/mysql/data:/var/lib/mysql
      - ./data:/var/lib/mysql